{id:"q-0000",cat:"math",diff:"easy",q:"If A = {1,2,3} and B = {3,4,5}, what is A ∩ B?",opts:["{1,2,3,4,5}","{3}","{1,2}","{4,5}"],ans:1,exp:"A∩B contains elements in both: only 3."},
  {id:"q-0001",cat:"math",diff:"easy",q:"If |A|=5, |B|=7, and |A∩B|=2, what is |A∪B|?",opts:["14","10","12","9"],ans:1,exp:"|A∪B|=|A|+|B|−|A∩B|=5+7−2=10."},
  {id:"q-0002",cat:"math",diff:"easy",q:"Which is true for all sets A?",opts:["A∪A=∅","A∩A=∅","A∪∅=A","A∩U=∅"],ans:2,exp:"Union with empty set returns the set itself."},
  {id:"q-0003",cat:"math",diff:"medium",q:"How many subsets does a set of n elements have?",opts:["n","2n","n²","2ⁿ"],ans:3,exp:"Each element in or out → 2ⁿ."},
  {id:"q-0004",cat:"math",diff:"medium",q:"Power set of {1,2} is:",opts:["{{1},{2}}","{∅,{1},{2},{1,2}}","{1,2,3}","{1,2,12}"],ans:1,exp:"All subsets including ∅."},
  {id:"q-0005",cat:"math",diff:"easy",q:"P→Q is false when:",opts:["P true, Q true","P true, Q false","P false, Q true","P false, Q false"],ans:1,exp:"Only when antecedent true, consequent false."},
  {id:"q-0006",cat:"math",diff:"easy",q:"Which is logically equivalent to P→Q?",opts:["Q→P","¬P∨Q","P∧Q","¬P∧¬Q"],ans:1,exp:"Material implication."},
  {id:"q-0007",cat:"math",diff:"medium",q:"Contrapositive of 'If rains, umbrella' is:",opts:["If umbrella, rains","If not rains, no umbrella","If no umbrella, no rain","None"],ans:2,exp:"Flip and negate."},
  {id:"q-0008",cat:"math",diff:"easy",q:"∀x P(x) means:",opts:["There exists x with P(x)","P(x) for some x","P(x) for every x","P(x) false"],ans:2,exp:"Universal quantifier."},
  {id:"q-0009",cat:"math",diff:"easy",q:"∃x P(x) is false when:",opts:["At least one x satisfies P","No x satisfies P","All x satisfy P","P undefined"],ans:1,exp:"Existential: true if any element satisfies."},
  {id:"q-0010",cat:"math",diff:"medium",q:"¬(P∧Q) is equivalent to:",opts:["¬P∧¬Q","¬P∨¬Q","P∨Q","P→Q"],ans:1,exp:"De Morgan."},
  {id:"q-0011",cat:"math",diff:"medium",q:"¬(P∨Q) is equivalent to:",opts:["¬P∨¬Q","¬P∧¬Q","P∧Q","P→Q"],ans:1,exp:"De Morgan."},
  {id:"q-0012",cat:"math",diff:"easy",q:"A function is injective if:",opts:["f(a)=f(b)⇒a=b","Every codomain element hit","f continuous","f monotonic"],ans:0,exp:"One-to-one."},
  {id:"q-0013",cat:"math",diff:"easy",q:"A function is surjective if:",opts:["Every input has output","Every codomain element has preimage","Invertible","Linear"],ans:1,exp:"Onto."},
  {id:"q-0014",cat:"math",diff:"medium",q:"A bijection from {1,2,3} to {a,b,c}:",opts:["Must be permutation","All same output","No inverse","Undefined"],ans:0,exp:"Same-size finite sets."},
  {id:"q-0015",cat:"math",diff:"easy",q:"sin²θ + cos²θ =",opts:["0","1","2","sin2θ"],ans:1,exp:"Pythagorean identity."},
  {id:"q-0016",cat:"math",diff:"easy",q:"sin(90°) =",opts:["0","1/2","1","√3/2"],ans:2,exp:"sin π/2 = 1."},
  {id:"q-0017",cat:"math",diff:"medium",q:"cos(60°) =",opts:["1/2","√3/2","1","0"],ans:0,exp:"cos π/3 = 1/2."},
  {id:"q-0018",cat:"math",diff:"medium",q:"sin(2θ) =",opts:["2 sinθ cosθ","sin²θ−cos²θ","2 sinθ","2 cosθ"],ans:0,exp:"Double angle."},
  {id:"q-0019",cat:"math",diff:"medium",q:"cos(2θ) =",opts:["1−2sin²θ","2 sinθ cosθ","sin²θ","1+2sin²θ"],ans:0,exp:"cos2θ identity."},
  {id:"q-0020",cat:"math",diff:"hard",q:"tan(A+B) =",opts:["(tanA+tanB)/(1−tanA·tanB)","(tanA−tanB)/(1+tanA·tanB)","tanA·tanB","tanA+tanB"],ans:0,exp:"Addition formula."},
  {id:"q-0021",cat:"math",diff:"easy",q:"log₁₀(100) =",opts:["1","2","10","100"],ans:1,exp:"10²=100."},
  {id:"q-0022",cat:"math",diff:"easy",q:"ln(e³) =",opts:["1","3","e","3e"],ans:1,exp:"ln(eˣ)=x."},
  {id:"q-0023",cat:"math",diff:"medium",q:"log_b(xy) =",opts:["log_b x · log_b y","log_b x + log_b y","log_b x − log_b y","log_b(x+y)"],ans:1,exp:"Product rule."},
  {id:"q-0024",cat:"math",diff:"medium",q:"log_b(xⁿ) =",opts:["n·log_b x","log_b x + n","n + log_b x","(log_b x)ⁿ"],ans:0,exp:"Power rule."},
  {id:"q-0025",cat:"math",diff:"hard",q:"Compute log₂(8):",opts:["1","3","4","8"],ans:1,exp:"2³=8."},
  {id:"q-0026",cat:"math",diff:"medium",q:"Solve e^(2x) = 7. x =",opts:["ln 7","(ln 7)/2","2 ln 7","e^7"],ans:1,exp:"2x = ln 7."},
  {id:"q-0027",cat:"math",diff:"easy",q:"i² =",opts:["1","−1","i","0"],ans:1,exp:"Definition."},
  {id:"q-0028",cat:"math",diff:"medium",q:"Conjugate of z=3+4i:",opts:["−3+4i","3−4i","−3−4i","4+3i"],ans:1,exp:"Flip imaginary."},
  {id:"q-0029",cat:"math",diff:"medium",q:"|3+4i| =",opts:["1","5","7","25"],ans:1,exp:"√(9+16)=5."},
  {id:"q-0030",cat:"math",diff:"hard",q:"e^(iπ) + 1 =",opts:["0","1","2","i"],ans:0,exp:"Euler."},
  {id:"q-0031",cat:"math",diff:"hard",q:"3 cube roots of unity sum to:",opts:["0","1","3","i"],ans:0,exp:"Sum is 0."},
  {id:"q-0032",cat:"math",diff:"medium",q:"If A⊆B and B⊆A, then:",opts:["Disjoint","A=B","A empty","B empty"],ans:1,exp:"Antisymmetry."},
  {id:"q-0033",cat:"math",diff:"easy",q:"(A∪B)ᶜ =",opts:["Aᶜ∪Bᶜ","Aᶜ∩Bᶜ","A∩B","A−B"],ans:1,exp:"De Morgan for sets."},
  {id:"q-0034",cat:"math",diff:"medium",q:"|{1,2,3}×{a,b}| =",opts:["5","6","9","3"],ans:1,exp:"3·2=6."},
  {id:"q-0035",cat:"math",diff:"easy",q:"Domain of f(x)=1/x:",opts:["All reals","Reals except 0","x>0","x≥0"],ans:1,exp:"x=0 undefined."},
  {id:"q-0036",cat:"math",diff:"easy",q:"Range of f(x)=x²:",opts:["All reals","[0,∞)","(0,∞)","R⁺"],ans:1,exp:"Squares ≥0."},
  {id:"q-0037",cat:"math",diff:"medium",q:"f(g(x)) with f=x², g=x+1:",opts:["x²+1","(x+1)²","x²+x+1","2x+1"],ans:1,exp:"f(g(x))=(x+1)²."},
  {id:"q-0038",cat:"math",diff:"easy",q:"How many primes ≤ 10?",opts:["3","4","5","6"],ans:1,exp:"2,3,5,7."},
  {id:"q-0039",cat:"math",diff:"medium",q:"GCD(12,18) =",opts:["2","3","6","36"],ans:2,exp:"6."},
  {id:"q-0040",cat:"math",diff:"medium",q:"LCM(4,6) =",opts:["2","12","24","10"],ans:1,exp:"12."},
  {id:"q-0041",cat:"math",diff:"easy",q:"Sum 1+2+...+10 =",opts:["45","55","65","100"],ans:1,exp:"n(n+1)/2."},
  {id:"q-0042",cat:"math",diff:"medium",q:"Sum of first n odd numbers =",opts:["n","n²","2n","n+1"],ans:1,exp:"1+3+...+(2n−1)=n²."},
  {id:"q-0043",cat:"math",diff:"easy",q:"0! =",opts:["0","1","undefined","n"],ans:1,exp:"By convention."},
  {id:"q-0044",cat:"math",diff:"medium",q:"P(5,2) =",opts:["10","20","25","60"],ans:1,exp:"5·4=20."},
  {id:"q-0045",cat:"math",diff:"easy",q:"C(5,2) =",opts:["10","20","25","5"],ans:0,exp:"10."},
  {id:"q-0046",cat:"math",diff:"easy",q:"sin(0) =",opts:["0","1","−1","undefined"],ans:0,exp:"sin 0 = 0."},
  {id:"q-0047",cat:"math",diff:"medium",q:"cos(π) =",opts:["0","1","−1","π"],ans:2,exp:"cos 180°=−1."},
  {id:"q-0048",cat:"math",diff:"easy",q:"e⁰ =",opts:["0","1","e","undefined"],ans:1,exp:"Any non-zero to 0."},
  {id:"q-0049",cat:"math",diff:"easy",q:"log_b(1) =",opts:["0","1","b","undefined"],ans:0,exp:"b⁰=1."},
  {id:"q-0050",cat:"math",diff:"medium",q:"log₂(32) = x. x =",opts:["4","5","6","8"],ans:1,exp:"2⁵=32."},
  {id:"q-0051",cat:"math",diff:"hard",q:"(f∘g)⁻¹ =",opts:["f⁻¹∘g⁻¹","g⁻¹∘f⁻¹","f∘g","(g∘f)⁻¹"],ans:1,exp:"Reverse order."},
  {id:"q-0052",cat:"math",diff:"medium",q:"Odd function satisfies:",opts:["f(−x)=f(x)","f(−x)=−f(x)","f(x)=0","f(x+y)=f(x)f(y)"],ans:1,exp:"Odd: f(−x)=−f(x)."},
  {id:"q-0053",cat:"math",diff:"medium",q:"Even function satisfies:",opts:["f(−x)=f(x)","f(−x)=−f(x)","f(x)=x","f(0)=1"],ans:0,exp:"Even: f(−x)=f(x)."},
  {id:"q-0054",cat:"math",diff:"hard",q:"lim (1+1/n)ⁿ =",opts:["1","e","π","0"],ans:1,exp:"Definition of e."},
  {id:"q-0055",cat:"math",diff:"medium",q:"Integers 1..100 divisible by 3:",opts:["33","34","32","30"],ans:0,exp:"⌊100/3⌋=33."},
  {id:"q-0056",cat:"math",diff:"easy",q:"7² mod 5 =",opts:["3","4","2","1"],ans:1,exp:"49 mod 5 = 4."},
  {id:"q-0057",cat:"math",diff:"hard",q:"Sum 2+5+8+...+29:",opts:["155","145","150","160"],ans:0,exp:"n=10, sum=155."},
  {id:"q-0058",cat:"math",diff:"medium",q:"1+2+4+8+16 =",opts:["31","32","30","16"],ans:0,exp:"2⁵−1."},
  {id:"q-0059",cat:"math",diff:"medium",q:"2ˣ = 16 ⇒ x =",opts:["2","4","8","16"],ans:1,exp:"2⁴=16."},
  {id:"q-0060",cat:"math",diff:"easy",q:"Sum of first 100 positive integers:",opts:["1000","4950","5050","10000"],ans:2,exp:"100·101/2=5050."},
  {id:"q-0061",cat:"math",diff:"medium",q:"If 3⁴ = 81, log₃(81) =",opts:["3","4","27","81"],ans:1,exp:"log₃(81)=4."},
  {id:"q-0062",cat:"math",diff:"easy",q:"Number of even numbers between 1 and 10:",opts:["4","5","6","3"],ans:1,exp:"2,4,6,8,10."},
  {id:"q-0063",cat:"math",diff:"medium",q:"tan(45°) =",opts:["0","1","√3","1/√3"],ans:1,exp:"tan(π/4)=1."},
  {id:"q-0064",cat:"math",diff:"hard",q:"sin(π/6) =",opts:["1/2","√3/2","1","0"],ans:0,exp:"sin 30°=1/2."},
  {id:"q-0065",cat:"math",diff:"hard",q:"Solution to 2x+3 = 11:",opts:["3","4","5","7"],ans:1,exp:"x=4."},
  {id:"q-0066",cat:"math",diff:"easy",q:"Decimal 0.25 as a fraction:",opts:["1/2","1/3","1/4","1/5"],ans:2,exp:"0.25 = 1/4."},
  {id:"q-0067",cat:"math",diff:"medium",q:"If f(x)=2x+1, f(3) =",opts:["5","6","7","8"],ans:2,exp:"f(3)=2·3+1=7."},
  {id:"q-0068",cat:"math",diff:"hard",q:"Number of ways to arrange 3 distinct books:",opts:["3","6","9","12"],ans:1,exp:"3!=6."},
  {id:"q-0069",cat:"math",diff:"medium",q:"Sum of geometric series 1+1/2+1/4+... =",opts:["1","2","3","∞"],ans:1,exp:"Sum = 1/(1−1/2)=2."},
  {id:"q-0070",cat:"math",diff:"easy",q:"Square root of 144:",opts:["10","11","12","14"],ans:2,exp:"12²=144."},
  {id:"q-0071",cat:"math",diff:"medium",q:"Next term: 2,4,8,16,...",opts:["18","24","32","30"],ans:2,exp:"2ⁿ."},
  {id:"q-0072",cat:"math",diff:"hard",q:"gcd(0,5) =",opts:["0","5","1","undefined"],ans:1,exp:"gcd(0,n)=|n|."},
  {id:"q-0073",cat:"math",diff:"easy",q:"Is 17 prime?",opts:["Yes","No","Sometimes","Depends"],ans:0,exp:"17 is prime."},
  {id:"q-0074",cat:"math",diff:"medium",q:"Area of triangle with base 4, height 3:",opts:["6","7","12","10"],ans:0,exp:"½·4·3=6."},
  {id:"q-0075",cat:"math",diff:"easy",q:"Circumference of circle, radius r:",opts:["2πr","πr²","πr","4πr"],ans:0,exp:"C=2πr."},
  {id:"q-0076",cat:"math",diff:"hard",q:"Area of circle, radius r:",opts:["2πr","πr²","πr","4πr"],ans:1,exp:"A=πr²."},